---
stages:
- name: Build Stage
  inputs:
  - type: git
    branch: main
  triggers:
  - type: commit  
  jobs:
  - name: Container build
    type: builder
    extension_id: ibm.devops.services.pipeline.container.builder
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
    IMAGE_NAME: ${CF_APP}
    USE_CACHED_LAYERS: 'true'
- name: Deploy
  inputs:
  - type: job
    stage: Build
    job: Container build
  properties:
  - name: ROUTE_HOSTNAME
    value: ${CF_APP}
    type: text
  jobs:
  - name: Group deploy
    type: deployer
    extension_id: ibm.devops.services.pipeline.docker.deploy.ice
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
    PORT: '8080'
    CONTAINER_NAME: ${CF_APP}
    DEPLOY_TYPE: red_black
